# Generated by Django 4.0.3 on 2022-04-08 06:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookadd', '0005_books_image'),
        ('customer', '0002_remove_carts_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivary_date', models.DateTimeField(default=datetime.timedelta(days=5))),
                ('status', models.CharField(choices=[('orderplaced', 'orderplaced'), ('dispatched', 'dispatched'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('order_cancelled', 'oredr_cancelled')], default='orderplaced', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookadd.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
