# Generated by Django 4.0.3 on 2022-04-09 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=123),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 11, 0, 4, 193364), null=True),
        ),
    ]
