# Generated by Django 4.0.3 on 2022-04-12 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_orders_expected_delivary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_delivary_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 11, 56, 2, 757847), null=True),
        ),
    ]
