# Generated by Django 4.0.2 on 2022-03-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookadd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='amount',
        ),
    ]
