# Generated by Django 4.0.2 on 2022-03-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookadd', '0002_rename_price_books_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
