# Generated by Django 4.0.2 on 2022-03-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookadd', '0003_rename_books_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Books',
        ),
    ]
